Repository codeit-team6/nomadia, pull requests merged in 2025-07, with the labels that each got.

#4 [style - 공통 css 구현]
  src/app/globals.css
  src/app/page.tsx
  tailwind.config.ts
Labels: 🎨 style

#6 [📁 chore] husky + lint-staged 설정
  .husky/pre-commit
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
Labels: 📁 chore

#10 [chore] 브랜드 컬러 수정, 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  .github/pull_request_template.md
  src/app/favicon.ico
  src/app/globals.css
Labels: 🎨 style, 📁 chore

#12 [✨Feat] footer 구현
  package-lock.json
  pnpm-lock.yaml
  public/images/icons/X.svg
  public/images/icons/alarm.svg
  public/images/icons/facebook.svg
  public/images/icons/instagram.svg
  public/images/icons/logo.svg
  public/images/icons/youtube.svg
  src/app/page.tsx
  src/shared/components/footer.tsx
Labels: 🎨 style, ✨ feature

#26 [✨Feat] 공통 컴포넌트 - 페이지네이션
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  .github/pull_request_template.md
  src/app/(test)/test-jyn/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/providers.tsx
  src/shared/components/.gitkeep
  src/shared/components/pagination/pagination.tsx
  src/shared/libs/utils/.gitkeep
Labels: ✨ feature, 📝 docs

#30 [♻️refactor] Footer 리팩토링
  pnpm-lock.yaml
  public/images/icons/nomadia.svg
  public/images/icons/profile.svg
  src/app/schema.json
  src/shared/components/footer.tsx
  src/shared/components/header.tsx
Labels: ♻️ refactor

#25 [✨Feat] login signup 로직 구현
  package.json
  pnpm-lock.yaml
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/features/auth/api/auth.api.ts
  src/features/auth/login/components/LoginForm.tsx
  src/features/auth/signup/components/SignupForm.tsx
  src/features/auth/stores/useAuthStore.ts
  src/features/auth/types/auth.types.ts
  src/features/auth/validators/auth.schema.ts
  src/shared/libs/api/axios.ts
Labels: ✨ feature

#35 [✨Feat] 공통 컴포넌트 - 모달 구현
  public/images/warning.svg
  src/app/(test)/test-jyn/page.tsx
  src/app/page.tsx
  src/features/auth/signup/components/SignupForm.tsx
  src/shared/components/modal/base-modal.tsx
  src/shared/components/modal/index.ts
  src/shared/components/modal/modal-button.tsx
  src/shared/components/modal/modal-footer.tsx
  src/shared/components/modal/modal-header.tsx
  src/shared/libs/stores/.gitkeep
  src/shared/libs/stores/useModalStore.ts
Labels: ✨ feature

#40 [✨Feat] 인풋 공통 컴포넌트 구현
  src/features/auth/signup/components/SignupForm.tsx
  src/features/auth/validators/auth.schema.ts
  src/shared/components/form-input/form-input.tsx
Labels: ✨ feature

#38 [♻️Refactor] 드롭다운 분리 및 ui 수정
  package-lock.json
  src/shared/components/dropdown.tsx
  src/shared/components/header.tsx
Labels: ♻️ refactor, 🎨 style, ✨ feature

#43 [🎨 ✨ Style] 회원가입, 로그인 UI 구현
  public/images/icons/eye-off.png
  public/images/icons/eye-on.png
  public/images/icons/kakao.png
  public/images/icons/logo-desktop.png
  public/images/icons/logo-kakao.png
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/features/auth/login/components/LoginForm.tsx
  src/features/auth/signup/components/SignupForm.tsx
  src/features/auth/validators/auth.schema.ts
  src/shared/components/form-input/form-input.tsx
Labels: 🎨 style, ✨ feature

#42 [✨Feat] 무한 스크롤
  src/app/(test)/test-modal/page.tsx
  src/app/(test)/test-scroll/getApi.ts
  src/app/(test)/test-scroll/page.tsx
  src/shared/components/pagination/pagination.tsx
  src/shared/libs/hooks/infiniteScroll/useInfiniteQuery.ts
  src/shared/libs/hooks/infiniteScroll/useInfiniteScroll.ts
Labels: ✨ feature

#49 [♻️ Refactor] 스프린트2 qa 피드백 요소 반영 작업
  next.config.ts
  src/app/globals.css
  src/features/activities/components/activity-card.tsx
  src/features/activities/components/banner-carousel.tsx
  src/features/activities/components/best-activities.tsx
  src/features/landing/components/experience-card.tsx
  src/features/landing/components/hero.tsx
  src/features/landing/components/landing-page.tsx
  src/features/landing/libs/types/types.ts
  src/features/landing/libs/utils/convertActToExp.ts
Labels: ♻️ refactor, 🎨 style

#48 [✨Feat] 메인화면 드롭다운 추가
  src/features/activities/components/all-activities.tsx
  src/shared/components/dropdown.tsx
Labels: 🎨 style, ✨ feature

#51 [♻️Refactor] 에러 페이지 리팩토링
  public/images/sad-laptop.svg
  src/app/(test)/test-error/page.tsx
  src/app/(test)/test-scroll/getApi.ts
  src/app/(test)/test-scroll/page.tsx
  src/app/error.tsx
  src/app/not-found.tsx
  src/features/(test)/getTestApi.ts
  src/features/(test)/testInstance.ts
  src/features/(test)/useErrorQuery.ts
Labels: ♻️ refactor, 🎨 style

#60 [✨Feat] 로딩스피너 개발 및 모든 체험 컴포넌트 내부 리팩토링
  src/features/activities/components/all-activities.tsx
  src/features/activities/components/banner-carousel.tsx
  src/features/activities/components/best-activities.tsx
  src/features/activities/libs/constants/activitiesConstants.ts
  src/features/landing/components/hero.tsx
  src/features/landing/components/landing-page.tsx
  src/shared/components/loading-spinner/loading-spinner.tsx
Labels: ♻️ refactor, ✨ feature

#62 [♻️Refactor] Variants 분리 및 Search ui 수정
  src/features/activities/components/search-result.tsx
  src/features/activities/components/search.tsx
  src/shared/libs/constants/searchVariant.ts
Labels: ♻️ refactor, 🎨 style, ✨ feature

#65 [✨Feat] 에러메시지 ui 개발 및 적용
  src/features/activities/components/all-activities.tsx
  src/features/activities/components/banner-carousel.tsx
  src/features/activities/components/best-activities.tsx
  src/features/landing/components/hero.tsx
  src/shared/components/error-message/error-message.tsx
Labels: ♻️ refactor, ✨ feature

#81 [♻️Refactor] 모달 컴포넌트 리팩토링
  src/app/(test)/test-modal/page.tsx
  src/shared/components/modal/base-modal.tsx
  src/shared/components/modal/components/base-modal.tsx
  src/shared/components/modal/components/index.ts
  src/shared/components/modal/components/modal-button.tsx
  src/shared/components/modal/components/modal-content.tsx
  src/shared/components/modal/components/modal-header.tsx
  src/shared/components/modal/components/modal-overlay.tsx
  src/shared/components/modal/index.ts
  src/shared/components/modal/libs/modalClasses.ts
  src/shared/components/modal/modal-footer.tsx
Labels: ♻️ refactor

#84 [✨ 🎨 Feat] 마이페이지 구현 - 1차
  public/images/icons/edit-button.png
  public/images/icons/icon-calendar.png
  public/images/icons/icon-list.png
  public/images/icons/icon-setting.png
  public/images/icons/icon-user.png
  public/images/icons/profile-default.png
  src/app/(my)/.gitkeep
  src/app/my/layout.tsx
  src/app/my/my-activities/page.tsx
  src/app/my/page.tsx
  src/app/my/profile/page.tsx
  src/app/my/reservation/page.tsx
  src/app/my/reserve-calendar/page.tsx
  src/features/auth/api/auth.api.ts
  src/features/auth/validators/auth.schema.ts
  src/features/my/components/sidebar.tsx
  src/features/my/profile/components/profile.tsx
  src/features/my/profile/lib/api/profile.api.ts
  src/features/my/profile/lib/types/types.ts
  src/shared/components/header.tsx
  src/shared/libs/hooks/useWindowSize.ts
Labels: 🎨 style, ✨ feature

#85 [✨Feat] 캘린더 컴포넌트 구현
  public/images/icons/arrow.svg
  src/app/(test)/test-calendar/hyun/page.tsx
  src/app/(test)/test-calendar/my/page.tsx
  src/app/(test)/test-calendar/page.tsx
  src/app/(test)/test-calendar/woo/page.tsx
  src/app/globals.css
  src/app/not-found.tsx
  src/features/(test)/mockReservation.ts
  src/features/(test)/mockSchedules.ts
  src/shared/components/calendar/components/arrow-button.tsx
  src/shared/components/calendar/components/calendar-for-form.tsx
  src/shared/components/calendar/components/calendar-with-reservations.tsx
  src/shared/components/calendar/components/day-of-week.tsx
  src/shared/components/calendar/components/days-of-month.tsx
  src/shared/components/calendar/components/not-this-month.tsx
  src/shared/components/calendar/libs/constants/calendarStyles.ts
  src/shared/components/calendar/libs/constants/monthName.ts
  src/shared/components/calendar/libs/types/data.ts
  src/shared/components/calendar/libs/utils/formatDateToYMD.ts
  src/shared/components/calendar/libs/utils/getMonthRange.ts
  src/shared/libs/stores/useCalendarStore.ts
Labels: ✨ feature

#87 [✨Feat] 예약 내역 UI 및 비즈니스 로직 개발
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/app/layout.tsx
  src/app/my/reservation/page.tsx
  src/features/(test)/getTestApi.ts
  src/features/activities/components/activity-card.tsx
  src/features/activities/components/all-activities.tsx
  src/features/activities/libs/api/getActListApi.ts
  src/features/activities/libs/hooks/useResActivitiesQuery.ts
  src/features/booking-detail/components/booking-card-actions.tsx
  src/features/booking-detail/components/booking-card-container.tsx
  src/features/booking-detail/components/booking-card.tsx
  src/features/booking-detail/components/booking-list.tsx
  src/features/booking-detail/components/booking-modal.tsx
  src/features/booking-detail/components/filter-buttons.tsx
  src/features/booking-detail/components/group-booking-card.tsx
  src/features/booking-detail/components/star-rating.tsx
  src/features/booking-detail/libs/api/bookingApi.ts
  src/features/booking-detail/libs/constants/bookingStatus.ts
  src/features/booking-detail/libs/hooks/useBookingQuery.ts
  src/features/booking-detail/libs/hooks/useCancelMutation.ts
  src/features/booking-detail/libs/hooks/usePostReviewMutation.ts
  src/features/booking-detail/libs/types/booking.ts
  src/features/booking-detail/libs/utils/bookingUtils.ts
  src/features/landing/components/cta.tsx
  src/features/landing/components/hero.tsx
  src/features/my/components/sidebar.tsx
  src/shared/components/modal/libs/modalClasses.ts
  src/shared/libs/hooks/useActivityQuery.ts
  src/shared/libs/stores/useModalStore.ts
  src/shared/libs/utils/formatPrice.ts
  src/shared/libs/utils/parseDate.ts
  src/shared/types/activity.ts
Labels: ✨ feature

#94 [✨Feat] 예약 현황 구현 - 1차
  src/app/layout.tsx
  src/app/my/reserve-calendar/page.tsx
  src/features/activities/libs/api/getReserveMonthApi.ts
  src/features/landing/components/header-wrapper.tsx
  src/shared/components/calendar/components/calendar-with-reservations.tsx
  src/shared/components/calendar/components/days-of-month.tsx
  src/shared/components/dropdown.tsx
  src/shared/components/header-wrapper.tsx
Labels: 🎨 style, ✨ feature, 🛠️ perfomance, 📁 chore

#101 [✨Feat] 내 체험 관리 ui 및 기능 구현
  public/images/icons/activity-default.svg
  public/images/icons/icon-calendar.png
  public/images/icons/icon-list.png
  public/images/icons/icon-setting.png
  public/images/icons/icon-star.svg
  public/images/icons/icon-user.png
  public/images/icons/plus-button.svg
  src/app/my/my-activities/page.tsx
  src/features/my/components/sidebar.tsx
  src/features/my/my-activities/components/delete-confirm-modal.tsx
  src/features/my/my-activities/components/my-activities-card.tsx
  src/features/my/my-activities/components/my-activities-list.tsx
  src/features/my/my-activities/lib/api/myActivities.api.ts
  src/features/my/my-activities/lib/types/types.ts
Labels: 🎨 style, ✨ feature

#107 ✨ feat: 체험 카드, 사진 클릭 시 체험 상세 페이지로 이동
  src/features/activities/components/activity-card.tsx
  src/features/activities/components/banner-carousel.tsx
Labels: ✨ feature

#103 [✨Feat] 알림 기능 구현
  src/features/activities/components/notification-button.tsx
  src/features/activities/libs/hooks/useNotifications.ts
  src/features/auth/types/notification.ts
  src/shared/components/header.tsx
  src/shared/components/modal/components/notification-modal.tsx
Labels: ✨ feature

#108 [ ✨Feat] 체험 상세 페이지
  package.json
  pnpm-lock.yaml
  public/images/icons/map-spot.svg
  public/images/icons/more.svg
  public/images/icons/star.svg
  src/app/activities/[id]/page.tsx
  src/features/activityId/components/map/address-with-map.tsx
  src/features/activityId/components/map/kakao-map.tsx
  src/features/activityId/components/owner-drop-down.tsx
  src/features/activityId/components/reservation-form.tsx
  src/features/activityId/components/reservation-modal.tsx
  src/features/activityId/components/reviews.tsx
  src/features/activityId/components/star.tsx
  src/features/activityId/components/sub-images.tsx
  src/features/activityId/libs/api/getActivityId.ts
  src/features/activityId/libs/api/getReviews.ts
  src/features/activityId/libs/api/getSchedules.ts
  src/features/activityId/libs/api/postReservationForm.ts
  src/features/activityId/libs/constants/variants.ts
  src/features/activityId/libs/hooks/useActivityIdQuery.ts
  src/features/activityId/libs/hooks/useReservationMutation.ts
  src/features/activityId/libs/hooks/useReviewsQuery.ts
  src/features/activityId/libs/hooks/useSchedulesQuery.ts
  src/features/activityId/libs/mockPageData.ts
  src/features/activityId/libs/mockReviewData.ts
  src/features/activityId/libs/types/ReviewsResponse.ts
  src/features/activityId/libs/types/activityInfo.ts
  src/features/activityId/libs/types/availableSchedule.ts
  src/features/activityId/libs/types/reservationType.ts
  src/features/activityId/libs/types/reviewResponse.ts
  src/features/activityId/libs/utils/formatRating.ts
  src/shared/components/calendar/components/calendar-for-form.tsx
  src/shared/components/calendar/components/calendar-with-reservations.tsx
  src/shared/components/dropdown.tsx
  src/shared/components/modal/components/adaptive-modal/adaptive-modal.tsx
  src/shared/components/modal/components/modal-content.tsx
  src/shared/libs/stores/useCalendarStore.ts
  tsconfig.json
Labels: ✨ feature

#112 [🐛Fix] onCellClick 에러 수정
  src/shared/components/calendar/components/calendar-with-reservations.tsx
Labels: 🐛 bug
