Repository codeit-team6/nomadia, pull requests merged in 2025-09, with the labels that each got.

#199 [✨Feat] 각 영역에 맞는 스켈레톤 ui 개발
  src/app/providers.tsx
  src/app/test-skeleton/page.tsx
  src/app/test-skeleton/test-skeleton.tsx
  src/features/activities/components/all-activities.tsx
  src/features/activities/components/banner-carousel.tsx
  src/features/activities/components/best-activities.tsx
  src/features/activities/libs/api/getActListApi.ts
  src/features/booking-detail/components/booking-card.tsx
  src/features/booking-detail/components/booking-list.tsx
  src/features/landing/components/hero.tsx
  src/features/my/my-activities/components/my-activities-list.tsx
  src/shared/components/skeleton/skeleton.tsx
  src/shared/libs/hooks/useActivityQuery.ts
  src/shared/libs/hooks/useLoadingErrorState.ts
Labels: ✨ feature

#202 [🐛Fix] QA(8/29) 반영
  src/app/my/reserve-calendar/page.tsx
  src/features/activities/components/all-activities.tsx
  src/features/activities/components/search.tsx
  src/features/activities/libs/stores/searchStore.ts
  src/features/reservation-state/components/content-reservation.tsx
  src/shared/components/header/header.tsx
Labels: 🐛 bug, ♻️ refactor

#206 [♻️Refactor] 0903 QA 진행 후 리팩토링 요소 반영
  src/app/activities/page-content.tsx
  src/app/my/layout.tsx
  src/app/my/my-activities/activity-registration/page.tsx
  src/app/test-skeleton/page.tsx
  src/app/test-skeleton/test-skeleton.tsx
  src/features/activities/components/banner-carousel.tsx
  src/features/activity-registration/libs/hooks/useImageMutation.ts
  src/features/activity-registration/libs/hooks/useRegistrationMutation.ts
  src/features/auth/login/components/LoginForm.tsx
  src/features/auth/signup/components/SignupForm.tsx
  src/features/booking-detail/components/booking-modal.tsx
  src/features/booking-detail/libs/hooks/usePostReviewMutation.ts
  src/features/my/activity-edit/components/activity-edit-form.tsx
  src/features/my/activity-edit/libs/hooks/useEditActivityMutation.ts
  src/features/my/profile/components/profile.tsx
  src/shared/components/auth/AuthGuard.tsx
  src/shared/components/skeleton/skeleton.tsx
Labels: 🐛 bug, ♻️ refactor, 🎨 style, ✨ feature

#204 [📝Docs] readme, 메타데이터 작성
  README.md
  public/images/.gitkeep
  public/images/icons/no-data.svg
  public/images/icons/profile-default.png
  public/images/icons/profile-default.svg
  public/images/og-image.png
  src/app/layout.tsx
  src/app/my/my-activities/page.tsx
  src/app/my/reservation/page.tsx
  src/app/my/reserve-calendar/page.tsx
  src/features/activityId/components/map/kakao-map.tsx
  src/features/booking-detail/components/booking-list.tsx
  src/features/landing/components/cta.tsx
  src/features/landing/components/hero.tsx
  src/features/landing/components/step-card.tsx
  src/features/my/components/sidebar.tsx
  src/features/my/my-activities/components/my-activities-list.tsx
  src/features/my/profile/components/profile.tsx
  src/shared/components/error-message/error-message.tsx
  src/shared/components/header/header.tsx
  src/shared/components/no-data/no-data.tsx
Labels: 📝 docs

#212 [♻️Refactor] 9/3 QA 피드백 반영
  README.md
  src/app/my/reserve-calendar/page.tsx
  src/features/activities/components/all-activities.tsx
  src/features/activityId/components/map/address-with-map.tsx
  src/features/activityId/components/map/kakao-map.tsx
  src/features/activityId/components/reservation-form/reservation-form.tsx
  src/features/activityId/components/reviews.tsx
  src/shared/components/header/header.tsx
  src/shared/components/skeleton/skeleton.tsx
Labels: 🐛 bug, 🎨 style, ✨ feature

#209 [🎨Style] 9/3 QA 피드백 반영 - 디자인
  src/app/(auth)/login/page.tsx
  src/app/my/reserve-calendar/page.tsx
  src/features/activities/components/search.tsx
  src/features/reservation-state/components/content-reservation.tsx
  src/features/reservation-state/components/empty-reservation.tsx
  src/shared/components/calendar/components/calendar-with-reservations.tsx
Labels: 🎨 style

#223 [📝Docs] 프로젝트 문서 추가
  README.md
  src/features/activityId/components/sub-images.tsx
  src/shared/components/calendar/components/calendar-for-form.tsx
  src/shared/components/modal/components/basic-modal/basic-modal.tsx
Labels: 🎨 style, 📝 docs
