Repository codeit-team6/nomadia, pull requests merged in 2025-08, with the labels that each got.

#118 [🐛Fix] 캘린더, 맵 에러케이스 처리 (7/31QA feedback)
  LICENSE
  src/app/(test)/test-error/page.tsx.bak
  src/app/activities/[id]/page.tsx
  src/features/activityId/components/map/kakao-map.tsx
  src/features/activityId/components/reservation-form.tsx
  src/features/activityId/components/reservation-modal.tsx
  src/features/activityId/libs/hooks/useIsTablet.ts
  src/features/activityId/libs/hooks/useReviewsQuery.ts
  src/features/activityId/libs/hooks/useSchedulesQuery.ts
  src/features/activityId/libs/types/availableSchedule.ts
  src/features/activityId/libs/utils/addReservation.ts
  src/shared/components/calendar/components/calendar-for-form.tsx
Labels: 🐛 bug, ✨ feature

#119 [♻️Refactor] 로그인 관련 오류 해결,
  src/app/my/my-activities/activity-registration/page.tsx
  src/app/my/my-activities/page.tsx
  src/features/auth/signup/components/SignupForm.tsx
  src/features/auth/validators/auth.schema.ts
  src/features/my/profile/components/profile.tsx
  src/features/my/profile/lib/hooks/useMyProfile.ts
  src/shared/components/auth/AuthGuard.tsx
  src/shared/components/header.tsx
  src/shared/libs/api/axios.ts
Labels: ♻️ refactor

#121 [✨Feat] search 상태 동기화
  src/features/activities/components/search.tsx
Labels: ✨ feature

#124 [♻️Refactor] qa 수정 요소 반영
  package.json
  pnpm-lock.yaml
  src/features/activity-registration/components/activity-registration-form.tsx
  src/features/activity-registration/components/date-scheduler.tsx
  src/features/activity-registration/components/image-upload-base.tsx
  src/features/activity-registration/libs/hooks/useImageMutation.ts
  src/features/activity-registration/libs/hooks/useRegistrationMutation.ts
  src/shared/components/form-input/form-input.tsx
  src/shared/libs/utils/parseDate.ts
Labels: 🐛 bug, ♻️ refactor

#135 [♻️Refactor134] starImage 컴포넌트 적용 (체험 카드)
  src/features/activities/components/activity-card.tsx
  src/features/activity-registration/components/activity-registration-form.tsx
  src/features/activity-registration/libs/hooks/useRegistrationMutation.ts
Labels: ♻️ refactor, 🎨 style

#140 [♻️🐛Refactor] 8/3 QA 피드백 반영
  .github/workflows/lighthouse-ci.yml
  .gitignore
  README.md
  lighthouserc.js
  package-lock.json
  package.json
  src/app/(auth)/.gitkeep
  src/app/(test)/test-calendar/hyun/page.tsx.bak
  src/app/(test)/test-calendar/my/page.tsx.bak
  src/app/(test)/test-calendar/page.tsx.bak
  src/app/(test)/test-calendar/woo/page.tsx.bak
  src/app/(test)/test-modal/page.tsx.bak
  src/app/(test)/test-scroll/page.tsx.bak
  src/features/(test)/getTestApi.ts
  src/features/(test)/mockReservation.ts
  src/features/(test)/mockSchedules.ts
  src/features/(test)/testInstance.ts
  src/features/(test)/useErrorQuery.ts
  src/features/activityId/components/owner-drop-down.tsx
  src/features/activityId/components/reservation-form.tsx
  src/features/activityId/components/reviews.tsx
  src/features/activityId/libs/mockPageData.ts
  src/features/activityId/libs/mockReviewData.ts
  src/features/activityId/libs/utils/formatDateToShortSlash.ts
  src/shared/components/calendar/components/arrow-button.tsx
  src/shared/components/calendar/components/calendar-for-form.tsx
  src/shared/components/calendar/components/day-of-week.tsx
  src/shared/components/calendar/components/not-this-month.tsx
  src/shared/components/modal/components/modal-button.tsx
  src/shared/components/pagination/pagination.tsx
Labels: 🐛 bug, ♻️ refactor, ✨ feature

#142 [✨ 🎨 Feat] 마이페이지 - 내 체험 수정 구현
  src/app/my/layout.tsx
  src/app/my/my-activities/activity-edit/[id]/page.tsx
  src/app/providers.tsx
  src/features/my/activity-edit/components/activity-edit-form.tsx
  src/features/my/activity-edit/libs/api/activity-edit.api.ts
  src/features/my/activity-edit/libs/hooks/useEditActivityMutation.ts
  src/features/my/activity-edit/libs/types/types.ts
  src/features/my/my-activities/components/my-activities-card.tsx
Labels: 🎨 style, ✨ feature

#151 ♻️ refactor: 예약 목록 LCP 개선 - 우선순위 이미지 및 캐싱 최적
  next.config.ts
  src/features/activities/components/activity-card.tsx
  src/features/activities/components/all-activities.tsx
  src/features/activities/components/banner-carousel.tsx
  src/features/activities/components/best-activities.tsx
  src/features/activities/components/search-result.tsx
  src/features/booking-detail/components/booking-card-container.tsx
  src/features/booking-detail/components/booking-card.tsx
  src/features/booking-detail/components/booking-list.tsx
  src/features/booking-detail/components/group-booking-card.tsx
  src/features/booking-detail/libs/hooks/useBookingQuery.ts
  src/shared/libs/utils/imageOptimization.ts
Labels: ♻️ refactor

#156 [🐛Fix] 8/4 QA 피드백 반영
  pnpm-lock.yaml
  src/app/my/my-activities/activity-edit/[id]/page.tsx
  src/app/my/reserve-calendar/page.tsx
  src/features/activityId/components/map/kakao-map.tsx
  src/features/activityId/components/reservation-form.tsx
  src/features/activityId/components/reservation-modal.tsx
  src/features/activityId/libs/utils/addReservation.ts
  src/features/booking-detail/libs/hooks/useBookingQuery.ts
  src/features/my/activity-edit/components/activity-edit-form.tsx
  src/shared/components/form-input/form-input.tsx
  src/shared/libs/types/.gitkeep
Labels: 🐛 bug

#158 [🐛Fix] 알림/캘린더 에러 수정
  pnpm-lock.yaml
  public/images/icons/no-alarm.svg
  src/app/my/reserve-calendar/page.tsx
  src/features/activities/components/notification-button.tsx
  src/shared/components/header.tsx
  src/shared/components/modal/components/adaptive-modal/content-reservation.tsx
  src/shared/components/modal/components/adaptive-modal/empty-reservation.tsx
  src/shared/components/modal/components/notification-modal.tsx
  src/shared/libs/stores/useNotificationStore.ts
  src/shared/types/reservation.ts
Labels: 🐛 bug

#160 [♻️Refactor] 상세페이지 UX 개선
  src/features/activityId/components/reservation-form.tsx
  src/features/activityId/components/reviews.tsx
  src/features/activityId/libs/utils/formatDateWithDots.ts
  src/shared/components/calendar/components/calendar-for-form.tsx
  src/shared/components/calendar/components/not-this-month.tsx
  src/shared/components/calendar/libs/constants/calendarStyles.ts
Labels: ♻️ refactor

#171 [🐛Fix] 0819 기준 최신 dev 에러 사항 해결 공유
  src/features/activities/components/activity-card.tsx
  src/features/activityId/components/reservation-form.tsx
  src/shared/libs/shadcn/components/ui/button.tsx
Labels: 🐛 bug

#178 Revert "[🐛Fix] 예약현황 리팩토링"
  src/app/layout.tsx
  src/app/my/reserve-calendar/page.tsx
  src/features/reservation-state/components/empty-reservation.tsx
  src/shared/components/dropdown/dropdown.tsx
  src/shared/components/footer/footer.tsx
  src/shared/components/header/header.tsx
Labels: 🐛 bug, 📁 chore

#184 [🐛Fix] 모달 에러(스크롤), 체험상세이미지 ui 변경
  src/app/activities/[id]/page.tsx
  src/app/my/layout.tsx
  src/app/my/reserve-calendar/page.tsx
  src/features/activityId/components/reservation-form/reservation-form.tsx
  src/features/activityId/components/sub-images-modal.tsx
  src/features/activityId/components/sub-images.tsx
  src/shared/components/modal/components/adaptive-modal/adaptive-modal.tsx
  src/shared/components/modal/components/basic-modal/basic-modal.tsx
  src/shared/components/modal/libs/hooks/useLockBodyScroll.ts
Labels: 🐛 bug, ✨ feature

#186 [♻️Refactor] 마지막 주 리팩토링 작업 내역
  src/app/globals.css
  src/features/activities/components/activity-card.tsx
  src/features/activities/components/best-activities.tsx
  src/features/activities/libs/utils/.gitkeep
  src/features/activities/libs/utils/navigation.ts
  src/features/activity-registration/components/activity-registration-form.tsx
  src/features/activity-registration/components/date-scheduler.tsx
  src/features/activity-registration/components/image-upload-base.tsx
  src/features/activity-registration/libs/hooks/useImageMutation.ts
  src/features/activityId/libs/types/reservationType.ts
  src/features/booking-detail/components/booking-card-actions.tsx
  src/features/booking-detail/components/booking-card-container.tsx
  src/features/booking-detail/components/booking-card.tsx
  src/features/booking-detail/components/booking-list.tsx
  src/features/booking-detail/components/booking-modal.tsx
  src/features/booking-detail/components/group-booking-card.tsx
  src/features/booking-detail/libs/types/booking.ts
  src/features/landing/components/cta.tsx
  src/features/landing/components/hero.tsx
  src/shared/components/form-input/form-input.tsx
  src/shared/libs/utils/imageOptimization.ts
  src/shared/libs/utils/parseDate.ts
  src/shared/types/reservation.ts
Labels: ♻️ refactor

#189 [✨Feat] 검색창 및 추가기능 수정
  src/app/activities/page-content.tsx
  src/features/activities/components/notification-button.tsx
  src/features/activities/components/search-result.tsx
  src/features/activities/components/search.tsx
  src/features/my/my-activities/components/logout-confirm-modal.tsx
  src/shared/components/header/header.tsx
  src/shared/types/activity.ts
Labels: ♻️ refactor, ✨ feature

#190 [♻️Refactor] 최적화 진행
  next.config.ts
  src/app/activities/page-content.tsx
  src/features/activities/components/activity-card.tsx
  src/features/activities/components/all-activities.tsx
  src/features/activities/components/banner-carousel.tsx
  src/features/activities/components/best-activities.tsx
  src/features/activities/components/price-display.tsx
  src/features/activities/components/rating-display.tsx
  src/features/activities/components/search-result.tsx
  src/features/activityId/libs/hooks/useReviewsQuery.ts
  src/features/landing/components/hero.tsx
  src/shared/components/index.ts
  src/shared/libs/hooks/useActivityQuery.ts
  src/shared/libs/utils/rating.ts
Labels: ♻️ refactor, 🛠️ perfomance
